### ISSUE TITLE
Source code missing, only documentation in repository

### ISSUE THREAD

**Issue by xuiqzy** [ArtsiomCh/KDocCleanRead#2]
This plugin is licensed under GPL3, but there is only the documentation, an example image and the license in the repository.
Did you forget to upload the source code?

**Comment by ArtsiomCh** [comment]
Thanks for pointing that out. No plans to issue source code so far. Changed license to custom EULA.

**Comment by xuiqzy** [comment]
Thanks for checking! You can do this for future releases, but the current release was made with the GPL3 license, so you have to provide a way to get the source code for that release, according to your chosen license at the time.

**Comment by xuiqzy** [comment]
Note that because you based your plugin on the JavaDoc Clean Read plugin which is licensed under the GPL3 copyleft license ( https://github.com/ArtsiomCh/JDCleanRead/blob/master/LICENSE ), you have to publish your plugin under the same license (see section 5c and 6 in the license: https://www.gnu.org/licenses/gpl-3.0.html ) and you cannot choose an own license for your derived work.
Edit: Sorry I just saw that you are the sole contributor to the JavaDoc Clean Read plugin and therefore have the copyright to it :D
(My last comment still applies though, you can't "undo" a gpl release of a software, e.g. in the jetbrains plugin store, without providing the source of that version)

**Comment by xuiqzy** [comment]
Could you please release the source code of the version published under the GNU GPL3 License to comply with it?
